# Generated by Django 5.2.1 on 2025-10-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_article"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-pub_date"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
