# Generated by Django 5.2.1 on 2025-10-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0003_alter_article_options_alter_article_pub_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("body", models.TextField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
