# Generated by Django 5.2.1 on 2025-10-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0007_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="receipt",
            field=models.FileField(blank=True, null=True, upload_to="orders/receipts"),
        ),
    ]
