# Generated by Django 5.2.1 on 2025-10-12 11:22

import django.core.validators
import django.db.models.deletion
import shopapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0010_productimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "price"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Delivery address"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                related_name="orders", to="shopapp.product", verbose_name="Products"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="promocode",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Promo code"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="receipt",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="orders/receipts",
                verbose_name="Receipt",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Archived"),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, db_index=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.SmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Discount",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_index=True, max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=shopapp.models.product_preview_directory_path,
                verbose_name="Preview",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="description",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to=shopapp.models.product_images_directory_path,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="shopapp.product",
                verbose_name="Product",
            ),
        ),
    ]
